# Generated by Django 4.2.6 on 2023-11-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_extra_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='fecha_inicio',
        ),
    ]
